### PR TITLE
Fix indents in readme

### PR DESCRIPTION
**Pull request by akira6592**
Fix invalid indents and more.

### CODE REVIEW

**Review by p3ck — APPROVED** [review]
lgtm

**Review by alinabuzachis — APPROVED** [review]

**Comment by p3ck** [comment]
@akira6592 Can you rebase this PR and add a changelog fragment?

Thanks!

**Comment by akira6592** [comment]
@p3ck Thank you for comment. 
I rebased and added changelog fragment.

**Comment by akira6592** [comment]
Thank you for mering.

**Pull request merged**
