### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by alinabuzachis**
- Increase ansible-lint version to 6.22
- Increase ansible-core supported version
- Ensure that the naming of variables is correct between roles.

### CODE REVIEW

**Comment by GomathiselviS** [comment]
We should include meta/argument_specs.yml in the roles within the collection. This way, we can eliminate all the argument validation tasks in the roles. We can handle this as a separate PR.

**Comment by GomathiselviS** [comment]
@alinabuzachis I also think that we should handle the "roles variables renaming" in a distinct PR. I notice that #50  covers the renaming of variables in all the other roles. What are your thoughts on consolidating all this work into a single PR rather than having it in two separate ones?

**Comment by p3ck** [comment]
> @alinabuzachis I also think that we should handle the "roles variables renaming" in a distinct PR. I notice that #50 covers the renaming of variables in all the other roles. What are your thoughts on consolidating all this work into a single PR rather than having it in two separate ones?

I found additional prefixes that needed to be fixed and pushed #55 although it looks like some of it overlaps with #50

**Comment by p3ck** [comment]
Looks like a lot from #50 was already merged from 1931464663d9cf6d29fb36d3b140652c4eaf1552

**Comment by alinabuzachis** [comment]
> @alinabuzachis, I've noticed that @Bill Peck has initiated a separate PR for renaming role name variables. How would you feel about dedicating this PR exclusively to CI-related fixes?

This PR is intended to fix the CI issues only. Updating ansible-lint to 1.22 without fixing the naming of the leftover variables will raise errors.

**Comment by p3ck** [comment]
Excellent work @alinabuzachis !  Should we put this dependent on my pr then?  I am fine either way but I found a few more issues that I put in my PR.

**Comment by GomathiselviS** [comment]
Thanks, @alinabuzachis. I recommend merging your PR first and then proceeding with the role variable name changes in Bill's PR.

**Review by GomathiselviS — APPROVED** [review]
@alinabuzachis LGTM! Can you also update the references to the `operation` variable name in https://github.com/redhat-cop/cloud.azure_ops/blob/main/roles/azure_virtual_machine_with_public_ip/README.md#role-variables?

**Review by mandar242 — APPROVED** [review]

**Pull request merged**
